name: Build and Push Containers to ACR

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  ACR_LOGIN_SERVER: hwacr.azurecr.io         # <-- change if your ACR login server is different
  FRONTEND_IMAGE: hw-frontend
  BACKEND_IMAGE: hw-backend
  FRONTEND_DOCKERFILE: Dockerfile.frontend   # <-- adjust if your path/name differs
  BACKEND_DOCKERFILE: Dockerfile             # <-- adjust if your path/name differs
  CONTEXT_DIR: .                             

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # Login to ACR using admin credentials (from ACR > Access keys)
      - name: Docker login to ACR
        uses: azure/docker-login@v1
        with:
          login-server: ${{ env.ACR_LOGIN_SERVER }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      # Build & push FRONTEND
      - name: Build frontend image
        run: |
          docker build \
            -f "${{ env.FRONTEND_DOCKERFILE }}" \
            -t "${{ env.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE }}:latest" \
            -t "${{ env.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}" \
            "${{ env.CONTEXT_DIR }}"
      - name: Push frontend image
        run: |
          docker push "${{ env.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE }}:latest"
          docker push "${{ env.ACR_LOGIN_SERVER }}/${{ env.FRONTEND_IMAGE }}:${{ github.sha }}"

      # Build & push BACKEND
      - name: Build backend image
        run: |
          docker build \
            -f "${{ env.BACKEND_DOCKERFILE }}" \
            -t "${{ env.ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE }}:latest" \
            -t "${{ env.ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}" \
            "${{ env.CONTEXT_DIR }}"
      - name: Push backend image
        run: |
          docker push "${{ env.ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE }}:latest"
          docker push "${{ env.ACR_LOGIN_SERVER }}/${{ env.BACKEND_IMAGE }}:${{ github.sha }}"
