name: deploy-backend-to-app-service
on:
  push:
    branches: [ main ]

env:
  RG: hwt-rg                    # <-- change to your resource group
  ACR_NAME: hwtacr              # <-- change to your ACR name (no domain)
  ACR_LOGIN_SERVER: hwtacr.azurecr.io   # <-- change to your ACR login server
  WEBAPP_NAME: hwt-backend-app  # <-- change to your backend web app name
  IMAGE_NAME: hwt-backend       # any repo name in ACR
  DOCKERFILE_PATH: server/Dockerfile  # backend Dockerfile path
  CONTAINER_PORT: 3000          # update if different

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: ACR login
        uses: azure/CLI@v2
        with:
          inlineScript: |
            az acr login --name $ACR_NAME

      - name: Build and push image
        run: |
          docker build -f $DOCKERFILE_PATH -t $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }} .
          docker push $ACR_LOGIN_SERVER/$IMAGE_NAME:${{ github.sha }}

      - name: Point Web App to new image
        uses: azure/webapps-deploy@v3
        with:
          app-name: ${{ env.WEBAPP_NAME }}
          images: ${{ env.ACR_LOGIN_SERVER }}/${{ env.IMAGE_NAME }}:${{ github.sha }}
